### ISSUE TITLE
第五章变化中，仿射变换中，关于矩阵的描述有些问题。

### ISSUE THREAD

**Issue by halftrue** [qunten/iOS-Core-Animation-Advanced-Techniques#64]
https://github.com/AttackOnDobby/iOS-Core-Animation-Advanced-Techniques/blob/master/5-%E5%8F%98%E6%8D%A2/%E5%8F%98%E6%8D%A2.md#仿射变换
第五章变化中，仿射变换中，关于矩阵的描述有些问题。
原文如下：
用CGPoint的~~每一列和CGAffineTransform矩阵的每一行~~对应元素相乘再求和，就形成了一个新的CGPoint类型的结果。
应为：
用CGPoint的每一_**行**_和CGAffineTransform矩阵的每一**_列_**对应元素相乘再求和，就形成了一个新的CGPoint类型的结果。

**Comment by xuxiaokang** [comment]
可参照Apple文档中的计算结果：
![image](https://cloud.githubusercontent.com/assets/9929307/13745358/8e627cc0-ea28-11e5-9a70-acf9ba2ab161.png)

**Comment by siweidw** [comment]
行列式...
